# Embedded Systems - Spring 2019
# 
# Christian Bush (cbb330@msstate.edu), Spencer Callicott (sc2257@msstate.edu)
# Will Carroll (woc17@msstate.edu), Landon Casey (lec426@msstate.edu)
# Jack Fletcher (jdf469@msstate.edu)
#
# This is the build script for our embedded systems pipeline
#

image: tuxprogrammer/scons-xc:xc16

pipelines:
  branches: 
    '{default,lab4,lab5,pipeline-testing}':
      - step:
          script:
            - ./setup-lib.sh
            - /usr/bin/env python3 $(which scons)